[package]
name = "axum-logging-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "registry", "fmt"] }
 tower-http = { version = "0.6.6", features = ["request-id", "trace"] }
opentelemetry = { version = "0.30", features = ["trace", "metrics"] }
opentelemetry_sdk = { version = "0.30", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.22.0", features = ["rt-tokio", "isahc_collector_client"] }
opentelemetry-prometheus = "0.29.1"
opentelemetry-otlp = { version = "0.30.0", features = ["reqwest-client", "grpc-tonic"] }
tracing-opentelemetry = "0.31.0"
axum-tracing-opentelemetry = "0.29.0" # This line will be problematic, but I'll leave it for cargo check to report
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
opentelemetry-semantic-conventions = "0.30.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.12.20", features = ["json"] }
serde_json = "1.0"
hyper = "1.6.0"
tower = { version = "0.5.2", features = ["util"] }
