[package]
name = "axum-logging-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "registry", "fmt"] }
 tower-http = { version = "0.4", features = ["request-id", "trace"] }
opentelemetry = "0.20"
opentelemetry_sdk = { version = "0.20", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.19", features = ["rt-tokio", "isahc_collector_client"] }
opentelemetry-prometheus = "0.13"
opentelemetry-otlp = { version = "0.13", features = ["reqwest-client", "grpc-tonic"] }
tracing-opentelemetry = "0.20"
axum-opentelemetry = "0.4.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
hyper = "0.14"
tower = { version = "0.4", features = ["util"] }
