version: "3.9"

services:
  postgres:
    build:
      context: ./infra/postgres # Dockerfile 放的位置
      args:
        POSTGRES_VERSION: "16-alpine" # 或改成你要的版本
    container_name: dev-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./infra/postgres/.env
    volumes:
      # 資料持久化
      - pg_data:/var/lib/postgresql/data
      # 若想放自訂 SQL 初始化，打開下面這行
      # - ./infra/postgres/initdb:/docker-entrypoint-initdb.d:ro

volumes:
  pg_data:
