[package]
name = "infra_db_postgres"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
application = { path = "../application" }
sqlx = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
