[advisories]
ignore = [
    "RUSTSEC-2023-0071",  # RSA timing attack - from sqlx-mysql (we only use postgres)
    "RUSTSEC-2024-0437"   # protobuf recursion - from prometheus (waiting for upstream fix)
]